version: "3.4"

services:
  clone:
    build: ./services/clone
    environment:
      RSYNC_SERVER: rsync.opensuse.org
      RSYNC_MODULE: opensuse-full-with-factory
      RSYNC_USER: opensuse
      RSYNC_PASSWORD:
    volumes:
      - ./deploy/swarm/rsync-include-test.txt:/etc/rsync-include.txt
      - .opensuse:/srv/pub/opensuse/

  content:
    build: ./services/content
    ports:
      - "8873:873"
    volumes:
      - .opensuse:/srv/pub/opensuse/

  download:
    build: ./services/download
    ports:
      - "8080:80"
      - "8083:443"
    volumes:
      - ./services/download/fancyindex:/srv/www/fancyindex
      - .opensuse:/srv/pub/opensuse/
