version: "3.5"

services:
  download:
    image: opensuse-mirror-download
    volumes:
      - fancyindex:/srv/www/fancyindex
      - opensuse:/srv/pub/opensuse/
    networks:
      - traefik
    ulimits:
      nofile:
        soft: 120000
        hard: 120000
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 256M
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik
        # https config
        - traefik.http.routers.download-https.rule=Host(`download.something.com`) || Host(`rsync.something.com`)
        - traefik.http.routers.download-https.entrypoints=https
        - traefik.http.routers.download-https.tls=true
        - traefik.http.routers.download-https.service=download
        # http config
        - traefik.http.routers.download-http.rule=Host(`download.something.com`) || Host(`rsync.something.com`)
        - traefik.http.routers.download-http.entrypoints=http
        - traefik.http.routers.download-http.service=download
        # service config
        - traefik.http.services.download.loadbalancer.server.port=80

  content:
    image: opensuse-mirror-content
    volumes:
      - opensuse:/srv/pub/opensuse/
    networks:
      - traefik
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 64M
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik
        # tcp config
        - traefik.tcp.routers.content-tcp.rule=HostSNI(`*`)
        - traefik.tcp.routers.content-tcp.entrypoints=rsync
        - traefik.tcp.routers.content-tcp.service=content
        # service config
        - traefik.tcp.services.content.loadbalancer.server.port=873

  clone:
    image: opensuse-mirror-clone
    environment:
      # You need to request access to stage.opensuse.org
      # https://en.opensuse.org/openSUSE:Mirror_infrastructure#Access_for_registered_mirrors:_stage.opensuse.org
      RSYNC_SERVER: rsync.opensuse.org
      RSYNC_MODULE: opensuse-full-with-factory
      RSYNC_USER: opensuse
      RSYNC_PASSWORD:
      RSYNC_CHOWN: 1000:1000
    configs:
      - source: rsync-include
        target: /etc/rsync-include.txt
    volumes:
      - opensuse:/srv/pub/opensuse/
    networks:
      - traefik
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 */3 * * *"
        - "swarm.cronjob.skip-running=true"
        - "swarm.cronjob.replicas=1"
      restart_policy:
        condition: none

configs:
  rsync-include:
    external: true

networks:
  traefik:
    external: true

volumes:
  fancyindex:
    external: true
  opensuse:
    external: true
